### ISSUE TITLE
Can't comment out import line with single quotes

### ISSUE THREAD

**Issue by timkelty** [kswedberg/postcss-import#1] opened 2015-05-01 12:31 UTC
```
/*@import './mixins/**/*.css';*/
/*@import './base/extends.css';*/
```

``````
[08:31:07] Starting 'build:postcss'...
[08:31:07] Plumber found unhandled error:
 Error in plugin 'gulp-postcss'
Message:
    /Users/timkelty/Sites/****/app/assets/css/app.css:37:167: Unclosed quote

/*@import './mixins/**/*.css';*/
                                                                                                                                                                      ^
/*@import './base/extends.css';*/```
``````

**Comment by kswedberg** [comment] 2015-06-14 02:10
Hmmm. I think I see the problem. Inside `./mixins/**/*.css` there is a sneaky closing comment (`*/`).

**Comment by kswedberg** [comment] 2015-06-15 19:27
I don't think there is any way to get around this problem. It's caused by the `*/` within the glob pattern. I'm sure the css parser is considering that the end of the comment, so whatever comes after it is left dangling and unrecognized and therefore throws an error. Happens with double quotes, too. I can't imagine anyone would want to modify the parser to deal with commented globs, since globs aren't part of the css spec. 

I'm gonna close this now, but if you think I'm crazy, feel free to reopen with your diagnosis.

**Closed as completed by kswedberg** 2015-06-15 19:27 UTC
